### ISSUE TITLE
How to run locally

### ISSUE THREAD

**Issue by ansarikhurshid786** [trongthanh/trongthanh.github.com#3]

**Comment by ansarikhurshid786** [comment]
I am getting below given error :- 

Configuration file: D:/newOfficeSphere/_config.yml
  Dependency Error: Yikes! It looks like you don't have jekyll-sitemap or one of
 its dependencies installed. In order to use Jekyll as currently configured, you
'll need to install this gem. The full error message from Ruby is: 'cannot load
such file -- jekyll-sitemap' If you run into trouble, you can find helpful resou
rces at http://jekyllrb.com/help/!
jekyll 3.2.1 | Error:  jekyll-sitemap

**Comment by trongthanh** [comment]
Hi, just notice this post. 

Basically, this is source code of my personal (and copyrighted) blog to be published on Github Page. So it's for public viewing of the post source code only. If you're interested on the blog's theme, you can check out [this repo](https://github.com/trongthanh/startbootstrap-clean-blog-jekyll). There's getting started guide in the README of that repo.

**Comment by ansarikhurshid786** [comment]
Ok thank you
